### ISSUE TITLE
làm sao goi request api ở dòng này 

### ISSUE THREAD

**Issue by webvang** [oTranThanhNghia/SimpleAppReactNative1#1]
// call api
  // const response= yield call...

**Comment by webvang** [comment]
const response = {
    success: true,
    data: { id: 1 },
  };

on file loginSaga.js

**Comment by oTranThanhNghia** [comment]
Hiện tại mình chưa có api Login phía backend nhưng mình đã có 1 ví dụ khác để gọi api rồi nhé. Bạn vui lòng xem link dưới đây 

https://github.com/oTranThanhNghia/SimpleAppReactNative1/blob/f286cbc57a35563260d4894933a960bda9f8b5a1/app/features/home/sagas/homeSaga.js#L16
